# Copyright (C) 2022, Xilinx, Inc.
# Copyright (C) 2022, Advanced Micro Devices, Inc.
# SPDX-License-Identifier: Apache-2.0

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]


set_property MARK_DEBUG true [get_nets {U_App/mAxilReadSlaves[0][arready]}]
set_property MARK_DEBUG true [get_nets {U_App/mAxilReadSlaves[0][rvalid]}]
set_property MARK_DEBUG true [get_nets {U_App/mAxilWriteMasters[0][awvalid]}]
set_property MARK_DEBUG true [get_nets {U_App/mAxilWriteMasters[0][bready]}]
set_property MARK_DEBUG true [get_nets {U_App/mAxilWriteMasters[0][wvalid]}]
set_property MARK_DEBUG true [get_nets {U_App/mAxilWriteSlaves[0][awready]}]
set_property MARK_DEBUG true [get_nets {U_App/mAxilWriteSlaves[0][bvalid]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteSlaves[2][bvalid]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wvalid]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][bready]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][awvalid]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rvalid]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadMasters[2][rready]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadMasters[2][arvalid]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadMasters[2][araddr][4]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteSlaves[2][wready]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadMasters[2][araddr][2]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadMasters[2][araddr][3]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadMasters[2][araddr][5]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadMasters[2][araddr][6]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadMasters[2][araddr][7]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][0]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][1]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][2]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][3]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][4]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][7]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][3]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][0]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][awaddr][6]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][awaddr][7]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][awaddr][4]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][awaddr][5]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][awaddr][2]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rresp][1]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][5]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][6]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][7]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][9]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][8]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][10]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][11]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][12]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][13]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][14]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][15]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][16]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][17]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][18]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][19]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][20]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][21]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][22]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][23]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][24]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][25]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][26]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][27]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][28]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][29]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][30]}]
set_property MARK_DEBUG true [get_nets {U_App/axilReadSlaves[2][rdata][31]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][awaddr][3]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][1]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][2]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][4]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][5]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][6]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][8]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][10]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][11]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][12]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][13]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][14]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][15]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][16]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][17]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][18]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][19]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][20]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][21]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][22]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][23]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][24]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][25]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][26]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][27]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][28]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][29]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][30]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][31]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wdata][9]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wstrb][0]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wstrb][1]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wstrb][2]}]
set_property MARK_DEBUG true [get_nets {U_App/axilWriteMasters[2][wstrb][3]}]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list {U_Core/REAL_CPU.U_CPU/U_Pll/clkOut[1]}]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 3 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {U_App/mAxilReadMasters[0][arprot][0]} {U_App/mAxilReadMasters[0][arprot][1]} {U_App/mAxilReadMasters[0][arprot][2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {U_App/mAxilReadMasters[0]} {U_App/mAxilReadMasters[1]} {U_App/mAxilReadMasters[2]} {U_App/mAxilReadMasters[3]} {U_App/mAxilReadMasters[4]} {U_App/mAxilReadMasters[5]} {U_App/mAxilReadMasters[6]} {U_App/mAxilReadMasters[7]} {U_App/mAxilReadMasters[8]} {U_App/mAxilReadMasters[9]} {U_App/mAxilReadMasters[10]} {U_App/mAxilReadMasters[11]} {U_App/mAxilReadMasters[12]} {U_App/mAxilReadMasters[13]} {U_App/mAxilReadMasters[14]} {U_App/mAxilReadMasters[15]} {U_App/mAxilReadMasters[16]} {U_App/mAxilReadMasters[17]} {U_App/mAxilReadMasters[18]} {U_App/mAxilReadMasters[19]} {U_App/mAxilReadMasters[20]} {U_App/mAxilReadMasters[21]} {U_App/mAxilReadMasters[22]} {U_App/mAxilReadMasters[23]} {U_App/mAxilReadMasters[24]} {U_App/mAxilReadMasters[25]} {U_App/mAxilReadMasters[26]} {U_App/mAxilReadMasters[27]} {U_App/mAxilReadMasters[28]} {U_App/mAxilReadMasters[29]} {U_App/mAxilReadMasters[30]} {U_App/mAxilReadMasters[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {U_App/axilWriteMasters[2][wstrb][0]} {U_App/axilWriteMasters[2][wstrb][1]} {U_App/axilWriteMasters[2][wstrb][2]} {U_App/axilWriteMasters[2][wstrb][3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {U_App/axilWriteMasters[2][wdata][0]} {U_App/axilWriteMasters[2][wdata][1]} {U_App/axilWriteMasters[2][wdata][2]} {U_App/axilWriteMasters[2][wdata][3]} {U_App/axilWriteMasters[2][wdata][4]} {U_App/axilWriteMasters[2][wdata][5]} {U_App/axilWriteMasters[2][wdata][6]} {U_App/axilWriteMasters[2][wdata][7]} {U_App/axilWriteMasters[2][wdata][8]} {U_App/axilWriteMasters[2][wdata][9]} {U_App/axilWriteMasters[2][wdata][10]} {U_App/axilWriteMasters[2][wdata][11]} {U_App/axilWriteMasters[2][wdata][12]} {U_App/axilWriteMasters[2][wdata][13]} {U_App/axilWriteMasters[2][wdata][14]} {U_App/axilWriteMasters[2][wdata][15]} {U_App/axilWriteMasters[2][wdata][16]} {U_App/axilWriteMasters[2][wdata][17]} {U_App/axilWriteMasters[2][wdata][18]} {U_App/axilWriteMasters[2][wdata][19]} {U_App/axilWriteMasters[2][wdata][20]} {U_App/axilWriteMasters[2][wdata][21]} {U_App/axilWriteMasters[2][wdata][22]} {U_App/axilWriteMasters[2][wdata][23]} {U_App/axilWriteMasters[2][wdata][24]} {U_App/axilWriteMasters[2][wdata][25]} {U_App/axilWriteMasters[2][wdata][26]} {U_App/axilWriteMasters[2][wdata][27]} {U_App/axilWriteMasters[2][wdata][28]} {U_App/axilWriteMasters[2][wdata][29]} {U_App/axilWriteMasters[2][wdata][30]} {U_App/axilWriteMasters[2][wdata][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {U_App/axilWriteMasters[2][awaddr][0]} {U_App/axilWriteMasters[2][awaddr][1]} {U_App/axilWriteMasters[2][awaddr][2]} {U_App/axilWriteMasters[2][awaddr][3]} {U_App/axilWriteMasters[2][awaddr][4]} {U_App/axilWriteMasters[2][awaddr][5]} {U_App/axilWriteMasters[2][awaddr][6]} {U_App/axilWriteMasters[2][awaddr][7]} {U_App/axilWriteMasters[2][awaddr][8]} {U_App/axilWriteMasters[2][awaddr][9]} {U_App/axilWriteMasters[2][awaddr][10]} {U_App/axilWriteMasters[2][awaddr][11]} {U_App/axilWriteMasters[2][awaddr][12]} {U_App/axilWriteMasters[2][awaddr][13]} {U_App/axilWriteMasters[2][awaddr][14]} {U_App/axilWriteMasters[2][awaddr][15]} {U_App/axilWriteMasters[2][awaddr][16]} {U_App/axilWriteMasters[2][awaddr][17]} {U_App/axilWriteMasters[2][awaddr][18]} {U_App/axilWriteMasters[2][awaddr][19]} {U_App/axilWriteMasters[2][awaddr][20]} {U_App/axilWriteMasters[2][awaddr][21]} {U_App/axilWriteMasters[2][awaddr][22]} {U_App/axilWriteMasters[2][awaddr][23]} {U_App/axilWriteMasters[2][awaddr][24]} {U_App/axilWriteMasters[2][awaddr][25]} {U_App/axilWriteMasters[2][awaddr][26]} {U_App/axilWriteMasters[2][awaddr][27]} {U_App/axilWriteMasters[2][awaddr][28]} {U_App/axilWriteMasters[2][awaddr][29]} {U_App/axilWriteMasters[2][awaddr][30]} {U_App/axilWriteMasters[2][awaddr][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 2 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {U_App/axilReadSlaves[2][rresp][0]} {U_App/axilReadSlaves[2][rresp][1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {U_App/axilReadSlaves[2][rdata][0]} {U_App/axilReadSlaves[2][rdata][1]} {U_App/axilReadSlaves[2][rdata][2]} {U_App/axilReadSlaves[2][rdata][3]} {U_App/axilReadSlaves[2][rdata][4]} {U_App/axilReadSlaves[2][rdata][5]} {U_App/axilReadSlaves[2][rdata][6]} {U_App/axilReadSlaves[2][rdata][7]} {U_App/axilReadSlaves[2][rdata][8]} {U_App/axilReadSlaves[2][rdata][9]} {U_App/axilReadSlaves[2][rdata][10]} {U_App/axilReadSlaves[2][rdata][11]} {U_App/axilReadSlaves[2][rdata][12]} {U_App/axilReadSlaves[2][rdata][13]} {U_App/axilReadSlaves[2][rdata][14]} {U_App/axilReadSlaves[2][rdata][15]} {U_App/axilReadSlaves[2][rdata][16]} {U_App/axilReadSlaves[2][rdata][17]} {U_App/axilReadSlaves[2][rdata][18]} {U_App/axilReadSlaves[2][rdata][19]} {U_App/axilReadSlaves[2][rdata][20]} {U_App/axilReadSlaves[2][rdata][21]} {U_App/axilReadSlaves[2][rdata][22]} {U_App/axilReadSlaves[2][rdata][23]} {U_App/axilReadSlaves[2][rdata][24]} {U_App/axilReadSlaves[2][rdata][25]} {U_App/axilReadSlaves[2][rdata][26]} {U_App/axilReadSlaves[2][rdata][27]} {U_App/axilReadSlaves[2][rdata][28]} {U_App/axilReadSlaves[2][rdata][29]} {U_App/axilReadSlaves[2][rdata][30]} {U_App/axilReadSlaves[2][rdata][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {U_App/axilReadMasters[2][araddr][0]} {U_App/axilReadMasters[2][araddr][1]} {U_App/axilReadMasters[2][araddr][2]} {U_App/axilReadMasters[2][araddr][3]} {U_App/axilReadMasters[2][araddr][4]} {U_App/axilReadMasters[2][araddr][5]} {U_App/axilReadMasters[2][araddr][6]} {U_App/axilReadMasters[2][araddr][7]} {U_App/axilReadMasters[2][araddr][8]} {U_App/axilReadMasters[2][araddr][9]} {U_App/axilReadMasters[2][araddr][10]} {U_App/axilReadMasters[2][araddr][11]} {U_App/axilReadMasters[2][araddr][12]} {U_App/axilReadMasters[2][araddr][13]} {U_App/axilReadMasters[2][araddr][14]} {U_App/axilReadMasters[2][araddr][15]} {U_App/axilReadMasters[2][araddr][16]} {U_App/axilReadMasters[2][araddr][17]} {U_App/axilReadMasters[2][araddr][18]} {U_App/axilReadMasters[2][araddr][19]} {U_App/axilReadMasters[2][araddr][20]} {U_App/axilReadMasters[2][araddr][21]} {U_App/axilReadMasters[2][araddr][22]} {U_App/axilReadMasters[2][araddr][23]} {U_App/axilReadMasters[2][araddr][24]} {U_App/axilReadMasters[2][araddr][25]} {U_App/axilReadMasters[2][araddr][26]} {U_App/axilReadMasters[2][araddr][27]} {U_App/axilReadMasters[2][araddr][28]} {U_App/axilReadMasters[2][araddr][29]} {U_App/axilReadMasters[2][araddr][30]} {U_App/axilReadMasters[2][araddr][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list U_App/axilReadMasters]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {U_App/axilReadMasters[2][arvalid]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list U_App/axilReadSlaves]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list U_App/axilWriteMasters]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {U_App/axilWriteMasters[2][awvalid]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {U_App/axilWriteMasters[2][bready]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list U_App/axilWriteSlaves]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {U_App/axilWriteSlaves[2][wready]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {U_App/mAxilReadMasters[0][arvalid]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {U_App/mAxilReadMasters[0][rready]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list U_App/mAxilReadSlaves]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {U_App/mAxilReadSlaves[0][rvalid]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list U_App/mAxilWriteMasters]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {U_App/mAxilWriteMasters[0][bready]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list {U_App/mAxilWriteMasters[0][wvalid]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list U_App/mAxilWriteSlaves]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list {U_App/mAxilWriteSlaves[0][bvalid]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets axilClk]
