name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:
  build:

    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Git LFS Pull
        run: |
          git lfs fetch 
          git lfs pull
      - name: build
        run: |
          source /data/Xilinx/Vivado/2023.2/settings64.sh
          for i in `find firmware/submodules -maxdepth 1 -mindepth 1 -type d`; do cd $i ; git lfs fetch ; git lfs pull ; cd - ; done
          cd firmware/targets/test_kv260
          export OVERRIDE_SUBMODULE_LOCKS=1
          make 
        shell: sh
