name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout github repo
      uses: actions/checkout@v4
      with:
        lfs: true
        submodules: recursive
          
    - name: Checkout LFS objects
        run: git lfs checkout
        
    - name: build
      run: |
        source /data/Xilinx/Vivado/2023.2/settings64.sh
        cd firmware/targets/test_kv260
        make 
      shell: sh
